// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CopyToClipboard(arg1:string):Promise<void>;

export function GetFiles(arg1:string,arg2:string):Promise<Array<models.FileList>>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function StartApp():Promise<models.Result>;
